apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-zmu7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-solc-tenant/test-app-lzir/devfile-sample-python-basic-zmu7@sha256:578d04ec6d772e627a3e8eaf9852b5be8b5cb2722c42b29230a3b87d60c37761
        name: my-python
        resources: {}
status: {}
